package com.internly.service;

import com.internly.dto.InternshipDtos.*; import com.internly.entity.*; import com.internly.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;

@Service public class InternshipService {
    private final InternshipRepository internships; private final CompanyRepository companies; private final SkillRepository skills;
    public InternshipService(InternshipRepository internships, CompanyRepository companies, SkillRepository skills) { this.internships=internships; this.companies=companies; this.skills=skills; }
    @Transactional(readOnly=true) public Page<InternshipResponse> browse(String search,String domain,String location,Pageable pageable) { return internships.browse(Internship.Status.ACTIVE, clean(domain), clean(location), clean(search), pageable).map(this::response); }
    @Transactional(readOnly=true) public List<InternshipResponse> adminList() { return internships.findAll(Sort.by(Sort.Direction.DESC,"id")).stream().map(this::response).toList(); }
    @Transactional(readOnly=true) public InternshipResponse getActive(Long id) { return response(internships.findByIdAndStatus(id, Internship.Status.ACTIVE).orElseThrow(() -> new IllegalArgumentException("Internship not found"))); }
    public InternshipResponse toResponseForRecommendation(Internship internship) { return response(internship); }
    @Transactional public InternshipResponse create(InternshipRequest r) { return response(save(new Internship(), r)); }
    @Transactional public InternshipResponse update(Long id, InternshipRequest r) { return response(save(internships.findById(id).orElseThrow(() -> new IllegalArgumentException("Internship not found")), r)); }
    @Transactional public void deactivate(Long id) { Internship i=internships.findById(id).orElseThrow(() -> new IllegalArgumentException("Internship not found")); i.setStatus(Internship.Status.INACTIVE); internships.save(i); }
    private Internship save(Internship i, InternshipRequest r) { i.setTitle(r.title().trim()); i.setDescription(r.description().trim()); i.setCompany(companies.findById(r.companyId()).orElseThrow(() -> new IllegalArgumentException("Company not found"))); i.setDomain(r.domain().trim()); i.setQualification(clean(r.qualification())); i.setEligibleBranches(clean(r.eligibleBranches())); i.setLocation(clean(r.location())); i.setWorkMode(clean(r.workMode())); i.setDurationWeeks(r.durationWeeks()); i.setStipend(r.stipend()); i.setApplicationDeadline(r.applicationDeadline()); i.setStatus(r.status() == null ? Internship.Status.DRAFT : r.status()); Set<Skill> required = new HashSet<>(); for (String name : r.requiredSkills()) { String normalized=normalize(name); required.add(skills.findByNormalizedName(normalized).orElseGet(() -> skills.save(Skill.builder().name(name.trim()).normalizedName(normalized).build()))); } i.setRequiredSkills(required); return internships.save(i); }
    private InternshipResponse response(Internship i) { return new InternshipResponse(i.getId(),i.getTitle(),i.getDescription(),new CompanyResponse(i.getCompany().getId(),i.getCompany().getName(),i.getCompany().getDescription(),i.getCompany().getWebsite(),i.getCompany().getLocation(),i.getCompany().getIndustry(),i.getCompany().isActive()),i.getDomain(),i.getQualification(),i.getEligibleBranches(),i.getLocation(),i.getWorkMode(),i.getDurationWeeks(),i.getStipend(),i.getApplicationDeadline(),i.getStatus(),i.getRequiredSkills().stream().map(Skill::getName).sorted(String.CASE_INSENSITIVE_ORDER).toList()); }
    private String normalize(String v) { return v.trim().replaceAll("\\s+"," ").toLowerCase(Locale.ROOT); } private String clean(String v) { return v == null || v.isBlank() ? null : v.trim(); }
}
